version: "3.1"
services:
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    ports:
      - "${METABASE_PORT}:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=h2
      - MB_CONFIG_FILE_PATH=/app/config.yml
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    networks:
      - dev-env
networks:
  dev-env:
    external: true
