version: "3.1"
services:
  spark:
    hostname: spark
    image: apache/spark:3.5.0
    container_name: spark
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark -p 7077 --webui-port 8080
    networks:
      - dev-env
    volumes:
      - ./jobs:/opt/spark/jobs
    ports:
      - "${SPARK_UI_PORT}:8080"
    #   - "${SPARK_MASTER_PORT}:7077"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077 --cores 4 --memory 4G
    depends_on:
      spark:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
    networks:
      - dev-env

networks:
  dev-env:
    external: true
