version: "3.1"
services:
  database:
    hostname: postgres-local
    container_name: database
    image: postgres:16.1
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql

    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    networks:
      - dev-env
networks:
  dev-env:
    external: true
